lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser_common do
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {CodeStatsWeb.LayoutView, :root})
    plug(:put_secure_browser_headers)
    plug(:protect_from_forgery)
    plug(CodeStatsWeb.RememberMePlug)
    plug(CodeStatsWeb.SetSessionUserPlug)
    plug(CodeStatsWeb.AdPlug)
    plug(CodeStatsWeb.ConsentPlug)
  end

  pipeline :browser_html do
    plug(:accepts, ["html"])
  end

  pipeline :browser_csv do
    plug(:accepts, ["csv"])
  end

  pipeline :browser_auth do
    plug(CodeStatsWeb.AuthRequiredPlug)
  end

  pipeline :browser_unauth do
    plug(CodeStatsWeb.AuthNotAllowedPlug)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :browser_api do
    plug(:fetch_session)
    plug(CodeStatsWeb.SetSessionUserPlug)
  end

  pipeline :api_machine_auth do
    plug(CodeStatsWeb.MachineAuthRequiredPlug)
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_html)
    pipe_through(:browser_common)

    get("/", PageController, :index)

    get("/api-docs", PageController, :api_docs)
    get("/tos", PageController, :terms)
    get("/plugins", PageController, :plugins)
    get("/changes", ChangesController, :changes)
    get("/support", SupportController, :page)

    get("/aliases", AliasController, :list)

    get("/battle", BattleController, :battle)

    scope "/" do
      pipe_through(:browser_unauth)

      get("/login", AuthController, :render_login)
      post("/login", AuthController, :login)
      get("/signup", AuthController, :render_signup)
      post("/signup", AuthController, :signup)
      get("/forgot-password", AuthController, :render_forgot)
      post("/forgot-password", AuthController, :forgot)
      get("/reset-password/:token", AuthController, :render_reset)
      put("/reset-password/:token", AuthController, :reset)
    end

    get("/logout", AuthController, :logout)

    live("/users/:username", ProfileLive, :profile_live)
    get("/users/:username/avatar", ProfileController, :profile_gravatar)

    scope "/my" do
      pipe_through(:browser_auth)

      get("/profile", ProfileController, :my_profile)

      get("/preferences", PreferencesController, :edit)
      put("/preferences", PreferencesController, :do_edit)
      delete("/preferences", PreferencesController, :delete)

      get("/machines", MachineController, :list)
      post("/machines", MachineController, :add)
      get("/machines/:id", MachineController, :view_single)
      put("/machines/:id", MachineController, :edit)
      delete("/machines/:id", MachineController, :delete)
      post("/machines/:id/activate", MachineController, :activate)
      post("/machines/:id/deactivate", MachineController, :deactivate)
      post("/machines/:id/key", MachineController, :regen_machine_key)

      get("/consent", TermsController, :ask_consent)
      post("/consent", TermsController, :set_consent)
      delete("/consent-delete", TermsController, :delete_account)
    end
  end

  scope "/", CodeStatsWeb do
    pipe_through(:browser_csv)
    pipe_through(:browser_common)
    pipe_through(:browser_auth)

    get("/my/pulses", PulseController, :list)
    get("/my/private", ProfileController, :export_private)
  end

  scope "/" do
    pipe_through(:api)
    pipe_through(:browser_api)

    forward("/profile-graph", Absinthe.Plug, schema: CodeStats.Profile.PublicSchema)
    forward("/profile-graphiql", Absinthe.Plug.GraphiQL, schema: CodeStats.Profile.PublicSchema)
  end

  scope "/api", CodeStatsWeb do
    pipe_through(:api)

    get("/users/:username", ProfileController, :profile_api)

    scope "/my" do
      pipe_through(:api_machine_auth)

      post("/pulses", PulseController, :add)
    end
  end
end

lib/code_stats_web/templates/page/api_docs.html.eex
<div class="stripe">
  <h1>
    API documentation <sup>(v. 1.0.1)</sup>
  </h1>

  <h2>
    Table of Contents
  </h2>

  <p>
    <ol>
      <li>
        <a href="#basics">Basics</a>
      </li>
      <li>
        <a href="#terms">Terms</a>
      </li>
      <li>
        <a href="#auth">Authentication</a>
      </li>
      <li>
        <a href="#profile">Endpoint: Profile</a>
      </li>
      <li>
        <a href="#pulse">Endpoint: Pulse</a>
      </li>
    </ol>
  </p>

  <h2>
    Basics <a id="basics" href="#basics">#</a>
  </h2>

  <h3>Beta</h3>

  <p>
    For all your API testing needs, especially when testing adding new XP into the system, use the <a href="https://beta.codestats.net/" target="_blank">beta instance</a>.
  </p>

  <h3>API version</h3>

  <p>
    The API follows <a href="http://semver.org/">Semantic Versioning</a>. That means bugfixes bump the patch version, backwards compatible features bump the minor version and backwards incompatible changes bump the major version.
  </p>

  <h3>Protocol</h3>

  <p>
    All requests are made using HTTP and use JSON to serialize the data. Requests with payloads should send the payload as JSON in the request body. The responses are JSON, error responses will contain the key <code>error</code> which has the error message as value. The error message is a human readable message, not intended for automated parsing.
  </p>

  <h3>Path</h3>

  <p>
    All API paths are prefixed with <code>/api</code>.
  </p>

  <h3>HTTPS</h3>

  <p>
    All requests must be secured using HTTPS. Plain HTTP requests will not be accepted.
  </p>

  <h3>Timestamps</h3>

  <p>
    Datetime timestamps should be sent as RFC 3339 datetime values and include the timezone offset. Example: <code>2016-04-24T01:43:56+12:00</code>.
  </p>

  <h2>
    Terms <a id="terms" href="#terms">#</a>
  </h2>

  <h3>XP</h3>

  <p>
    Programming gives users <em>experience points</em>, i.e. XP. A certain amount of XP corresponds to a certain level. In Code::Stats, each keystroke that creates or deletes a character gives 1 XP, so a client should keep an XP counter and add to it on each such keystroke. Operating on many characters at once, such as when deleting highlighted text, is counted as 1 XP, if made possible by the editor's API. An XP value is a positive integer.
  </p>

  <h3>Level</h3>

  <p>
    A <em>level</em> is a human readable indicator of progress. It is calculated from XP and its only purpose is to make an amount of XP more meaningful for a user. The read API does not provide levels, so it is the client's job to calculate the levels of a user.
  </p>

  <p>
    Levels are calculated with the following pseudocode formula:
  </p>

  <pre><code>LEVEL_FACTOR = 0.025

// Get level for given XP
int get_level(float xp) {
  return to_int(floor(LEVEL_FACTOR * sqrt(xp)))
}</code></pre>

  <p>
    For more examples of level calculations, see <a href="https://gitlab.com/code-stats/code-stats/-/blob/master/lib/code_stats/xp/xp_calculator.ex">CodeStats.Language.XPCalculator</a>.
  </p>

  <h3>Language</h3>

  <p>
    XP is always tied to a <em>language</em>. This can be a programming language, but also some other syntax edited by the users, such as Markdown or JSON. Detecting the active language is the client's responsibility. This can be done, for example, based on the active syntax highlighting language or the file's extension. Languages are referred to by their names as strings.
  </p>

  <h3>Pulse</h3>

  <p>
    A <em>pulse</em> is a collection of XPs for different languages. Pulses should be added periodically by the client and should contain the languages used and the XPs accumulated since the last pulse. They should also contain the time the pulse was created. This way they can be sent later, if the user's Internet connection is down for the moment. Pulses that are more than a week old will not be accepted by the API.
  </p>

  <h2>
    Authentication <a id="auth" href="#auth">#</a>
  </h2>

  <p>
    Code::Stats uses simple token authentication. A single token authenticates both a user and the machine they are using. It is signed to prevent tampering and unauthorized creation of tokens matching other users' information. To generate a token, you need to create a new machine from the <a href="<%= Routes.machine_path(@conn, :list) %>">Machine control panel</a>. A token looks like this:
  </p>

  <pre><code>SFMyNTY.OEotWWdnPT0jI01qaz0.X0wVEZquh8Ogau1iTtBihYqqL71FD8N6p5ChQiIpaxQ</code></pre>

  <p>
    In all API requests that require authentication, the token must be added using the HTTP header <code>X-API-Token</code>. Here is an example request sent with the token (as printed by curl):
  </p>

  <pre><code>&gt; POST /api/my/pulses HTTP/1.1
&gt; Host: codestats.net:443
&gt; User-Agent: curl/7.43.0
&gt; Accept: */*
&gt; X-API-Token: SFMyNTY.OEotWWdnPT0jI01qaz0.X0wVEZquh8Ogau1iTtBihYqqL71FD8N6p5ChQiIpaxQ
&gt; Content-Type: application/json
&gt; Content-Length: 113</code></pre>

  <h2>
    Endpoint: Profile <a id="profile" href="#profile">#</a>
  </h2>

  <h3>
    Read public user's information
  </h3>

  <p>
    <code>GET <%= Routes.profile_path(@conn, :profile_api, "username") %></code>
  </p>

  <p>
    Retrieves the information of the specified user. If the user does not exist or their profile is private, <code>HTTP 404</code> will be returned. An example request that also shows the returned data format:
  </p>

  <pre><code>GET /api/users/Nicd HTTP/1.1

{
  "user": "Nicd",
  "total_xp": 3073421,
  "new_xp": 3289,
  "machines": {
    "Työkone": {
      "xps": 246116,
      "new_xps": 3289
    },
    "Best Machine": {
      "xps": 2827305,
      "new_xps": 0
    }
  },
  "languages": {
    "💩": {
      "xps": 1767278,
      "new_xps": 0
    },
    "XML": {
      "xps": 15,
      "new_xps": 0
    },
    "Plaintext": {
      "xps": 3429,
      "new_xps": 3289
    }
  },
  "dates": {
    "2016-12-31": 3289,
    "2016-08-24": 26700
  }
}</code></pre>

  <p>
    <strong>Returns</strong> user profile data as JSON. In the data, <code>new_xps</code> is XP gained in the last 12 hours.
  </p>

  <h2>
    Endpoint: Pulse <a id="pulse" href="#pulse">#</a>
  </h2>

  <h3>
    Add pulse <sup>(authn required)</sup>
  </h3>

  <p>
    <code>POST <%= Routes.pulse_path(@conn, :add) %></code>
  </p>

  <p>
    Adds a new <em>Pulse</em> to the system. The client should send a pulse periodically when the user is programming. The payload should be a list of languages and their accumulated XP since the last successful pulse. The pulse must also contain a <code>coded_at</code> timestamp that signifies when the pulse was generated. This allows sending the pulse later, if the Internet connection is momentarily cut.
  </p>

  <p>
    <strong>Note:</strong> The <code>coded_at</code> timestamp <strong>MUST</strong> be in the user's local time with their local UTC offset. Do not convert the time to UTC before sending it to the API.
  </p>

  <p>
    Note: The <code>coded_at</code> timestamp must be no older than a week. Any older timestamps will result in an error. Timestamps in the future will be ignored, their <code>coded_at</code> will be set to the current moment.
  </p>

  <p>
    Example payload:
  </p>

  <pre><code>{
  "coded_at": "2016-04-24T01:43:56+12:00",
  "xps": [
    {"language": "C++",    "xp": 15},
    {"language": "Elixir", "xp": 30},
    {"language": "EEx",    "xp": 3}
  ]
}</code></pre>

  <p><strong>Returns</strong> <code>HTTP 201</code> and <code>{"ok": "Great success!"}</code> on success.</p>
</div>

lib/code_stats_web/templates/page/terms.html.eex
<h2>Table of contents</h2>

<ol>
  <li><a href="#privacy">Privacy policy</a></li>
  <li><a href="#terms">Terms of service</a></li>
</ol>

<h2>Privacy policy <a id="privacy" href="#privacy">#</a></h2>

<p>
  <%= get_conf(:site_name) %> stores user data to provide its services. This document describes the data storage and usage policies.
</p>

<h3>Name and contact details of the personal data register holder</h3>

<dl>
  <dt>Organization</dt>
  <dd>Tmi AhlCode</dd>

  <dt>Finnish business ID</dt>
  <dd>3133797-6</dd>

  <dt>Email address</dt>
  <dd>ceo ⓐⓣ ahlcode.fi</dd>
</dl>

<p>
  Inquiries about the register and the data contained should be directed to the above addresses.
</p>

<h3>Name of the register</h3>

<p><%= get_conf(:site_name) %> (later "the service") user database.</p>

<h3>Location of the register</h3>

<p>
  The user database is stored on a cloud server hosted by <a href="https://www.hetzner.com/rechtliches/impressum" target="_blank">Hetzner Online GmbH</a> in Finland.
</p>

<h3>The purpose of data collection</h3>

<p>
  Data is collected about the users of the service to enable and improve the service's functionality. User data is not used for any other purpose.
</p>

<h3>Data contained in the register</h3>

<p>
  The service collects the following personal data from the users:
</p>

<ul>
  <li>
    Username and password for authentication purposes. Stored as long as the user does not delete their account.
  </li>
  <li>
    Email address (optional) for notifying the user about important announcements related to the service and for account recovery in the case of a lost password. Stored as long as user doesn't delete their account or remove the email in preferences.
  </li>
  <li>
    Second email address (optional) to use for displaying Gravatar in user profile and related places. Not used for any other purpose. Stored as long as user doesn't delete their account or remove the email in preferences.
  </li>
  <li>
    IP addresses and browser user agent strings from both authenticated and unauthenticated users are stored in the server request logs for 4 weeks. They are used for statistical purposes and abuse prevention.
  </li>
</ul>

<h3>Data sources</h3>

<p>
  All data is provided by the user and their client software. No data is collected from other sources.
</p>

<h3>Sharing of data with 3<sup>rd</sup> parties</h3>

<p>
  Data is never shared with 3<sup>rd</sup> parties, except in the following cases:
</p>

<ul>
  <li>to send an email to a user from the service (the email address and the contents of the email must be transferred to the email delivery service),</li>
  <li>to store backups with a backup storage provider described later in this document, or</li>
  <li>to comply with an official, legal, written order from the Finnish authorities to release customer data (so far this has not happened).</li>
</ul>

<h3>Transfer of data to outside the EU or ETA</h3>

<p>
  Data will not be moved outside the EU or ETA, except in the following cases:
</p>

<ul>
  <li>to send an email to a user from the service (the email address and the contents of the email must be transferred to the email delivery service).</li>
</ul>

<h3>Security of the register</h3>

<p>
  Logins and communication with the server are secured with <abbr title="Secure Shell">SSH</abbr>. On the server, the database is protected by a further login known to only the register holder. Passwords in the database are hashed using <em>Bcrypt</em> with a randomized salt to prevent their decryption in case of a data breach. If a strong password is used, it cannot be feasibly decrypted.
</p>

<p>
  Physical security of the server in the datacenter is managed by Hetzner Online GmbH.
</p>

<h3>Register data requests</h3>

<p>
  All users of the register have a right to get a copy of the data stored about them. To get a copy, use the data export feature in the preferences page when logged into your account. If you are not logged in, send a free form written request to the data register holder described above.
</p>

<h3>Deletion of data and stopping of data processing</h3>

<p>
  If you wish to delete all your personal data from the register, use the account deletion feature in the preferences page. Your data will be deleted from the database immediately, and from any backups within 5 weeks.
</p>

<p>
  When you delete your account, your data is no longer processed by the service, except for the IP addresses and user agent strings collected in the server logs as mentioned earlier, and any unscrubbed analytics data as noted below.
</p>

<h3>Note about backups</h3>

<p>
  The service's filesystem is backed up daily. The backups are created and stored by Hetzner. Backups older than a week are automatically deleted.
</p>

<h3>Note about analytics</h3>

<p>
  The service uses <a href="https://gitlab.com/Nicd/tilastokeskus" target="_blank">Tilastokeskus</a> to store simple analytics data about its users. The data is stored on the same server and is not transferred to any outside party.
</p>

<p>
  The stored data includes the following:

  <ul>
    <li>IP address (for abuse prevention)</li>
    <li>Autogenerated session ID (stored in cookie, lasts for 15 minutes after last request)</li>
    <li>User-Agent header sent by browser</li>
    <li>Request URL</li>
    <li>Referer header sent by browser</li>
    <li>Screen resolution</li>
    <li>Timezone offset from UTC</li>
    <li>City and country based on GeoIP data</li>
  </ul>
</p>

<p>
  After 90 days, stored requests in the analytics data will be scrubbed to remove private information. This removes the IP address, full User-Agent header, and city from the data.
</p>

<p>
  If you wish to prevent the storage of your request information in the analytics data, use an extension such as <a href="https://github.com/gorhill/uBlock" target="_blank">uBlock Origin</a> to block requests to <code>/tilastokeskus/*</code> on this website.
</p>

<h3>Note about advertisements</h3>

<p>
  The service may contain advertisements. These advertisements are provided by <a href="https://www.ethicalads.io/" target="_blank">EthicalAds</a>. EthicalAds does not track you, and the ads are targeted based on the page content and geolocation. Please see <a href="https://www.ethicalads.io/privacy-policy/" target="_blank">EthicalAds'</a> privacy policy for more information.
</p>

<p>
  Advertisement providers are never given access to the data register itself.
</p>

<h3>Note about email</h3>

<p>
  Emails from the service are sent using <a href="http://www.mailgun.com/" target="_blank">Mailgun</a> by Rackspace Inc, a US based company. This means user details contained in the emails (such as the user's email address) are sent to the email service as a necessary part of the email delivery process. If you do not wish to have your email address sent to either of these services, you can remove your email address in the preferences.
</p>

<p>
  For more information, please see <a href="https://www.mailgun.com/gdpr" target="_blank">Mailgun's GDPR page</a>.
</p>

<h3>Note about Gumroad</h3>

<p>
  The paid account features of the service use <a href="https://gumroad.com" target="_blank">Gumroad</a> as the payment provider. Gumroad collects data to deliver its services. This data includes, among others (quoted from Gumroad privacy policy):

  <ul>
    <li>transactional information based on your activities on the Site as a buyer (such as item and content you purchase)</li>
    <li>payment information, such as credit card number</li>
    <li>your contact information (such as your name, user ID, email-address, and shipping, billing and other information you provide to purchase an item or receive delivery of an item)</li>
  </ul>
</p>

<p>
  When you click a link on the service to navigate to purchasing a paid account license on Gumroad, your usage of Gumroad will be subject to their privacy policy. For more information, please see <a href="https://gumroad.com/privacy" target="_blank">Gumroad's privacy policy</a>.
</p>

<h3>Changes to the privacy policy</h3>

<p>
  This page holds the most up to date version of the privacy policy. We ask that you check this page for changes regularly. In the case of major changes to the policy, all users that have given their email address will be notified by email beforehand.
</p>

<p>
  This privacy policy was last changed on the 8<sup>th</sup> of November 2022.
</p>

<h2>Terms of service <a id="terms" href="#terms">#</a></h2>

<p>
  <%= get_conf(:site_name) %> (later "the service") is a free service. Using it is a privilege, not a right. There is no <abbr title="Service level agreement">SLA</abbr> promised or implied.
</p>

<p>
  The rules of using the service:
</p>

<ol>
  <li>Don't hammer or attempt to DoS the API or the server or you will be banned.</li>
  <li>Don't try to insert fake XP for yourself through the API.</li>
  <li>Don't be mean to other people.</li>
  <li>Do check the source code of the service and the plugins and suggest improvements.</li>
  <li>Have fun.</li>
</ol>

lib/code_stats_web/templates/page/terms_page.html.eex
<div class="stripe" id="terms-stripe">
  <h1>Legal matters</h1>

  <%= render(CodeStatsWeb.PageView, "terms.html") %>
</div>